### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by EugenTepin** [ExtendScript/extendscript-es6-shim#3]
**Object**

- [ ] [Object.assign](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) (new method)
- [ ] [Object.is](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/is) (**RC do not implement?**)
- [ ] [Object.setPrototypeOf](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf) (new method)
- [ ] [Object.prototype.toString](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/toString) (**ES5 FIX ?**)
- [ ] [Object.freeze](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) (FIX)
- [ ] [Object.seal](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) (FIX)
- [ ] [Object.preventExtensions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions) (FIX)
- [ ] [Object.isFrozen](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/isFrozen) (FIX)
- [ ] [Object.isSealed](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/isSealed) (FIX)
- [ ] [Object.isExtensible](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/isExtensible) (FIX)
- [ ] [Object.getOwnPropertyDescriptor](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor)(FIX)
- [ ] [Object.getPrototypeOf](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf) (FIX)
- [ ] [Object.keys](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) (FIX)
- [ ] [Object.getOwnPropertyNames](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames) (FIX)

**Function**

- [x] [Function.name](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Function/name) **Implemented in ExtendScript engine, but anonymous function has name 'anonymous' rather than empty string**

**Array**

- [ ] [Array.prototype.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) verify code in repo
- [ ] [Array.of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/of)
- [ ] [Array.prototype.copyWithin](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin)
- [ ] [Array.prototype.fill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill)
- [ ] [Array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)
- [ ] [Array.prototype.findIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex)
- [ ] [Array.isArray()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)
